apiVersion: v1
kind: Service
metadata:
  name: {{ include "falco.fullname" . }}
  namespace: {{ include "falco.namespace" . }}
  labels:
    {{- include "falco.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 2802
      protocol: TCP
      name: ui
  selector:
    app.kubernetes.io/name: {{ include "falco.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: sidekick
