image:
  repository: falcosecurity/falco
  tag: "0.38.0"
  pullPolicy: IfNotPresent

driver:
  kind: modern_ebpf

falcosidekick:
  enabled: true
  image:
    repository: falcosecurity/falcosidekick
    tag: "2.28.0"
  ui:
    enabled: true
    image:
      repository: falcosecurity/falcosidekick-ui
      tag: "2.1.0"
    service:
      port: 2802

service:
  type: ClusterIP
  port: 2802

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: falco.vigilante.local
  tls:
    - secretName: falco-tls
      hosts:
        - falco.vigilante.local

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
