import assert from 'node:assert';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {
  getOllamaHost,
  compileMcpSecurityContext,
  saveAnalysisReport,
  DEFAULT_SYSTEM_PROMPT
} from '../src/engine/llm.js';
import { PRESET_ANALYSES, LLMView } from '../src/ui/LLMView.js';

console.log('🧪 Testing AI Security Analyst Engine (Ollama/Claude/GPT/Gemini)...');

// Test 1: getOllamaHost normalization
{
  const host1 = getOllamaHost({ ai: { ollama: { host: 'http://localhost:11434' } } });
  assert.strictEqual(host1, 'http://localhost:11434');

  const host2 = getOllamaHost({ ai: { ollama: { host: '192.168.1.100:11434/' } } });
  assert.strictEqual(host2, 'http://192.168.1.100:11434');
  console.log('✔ Test 1 passed: getOllamaHost correctly normalizes addresses and protocols.');
}

// Test 2: System prompt definition
{
  assert.ok(typeof DEFAULT_SYSTEM_PROMPT === 'string');
  assert.ok(DEFAULT_SYSTEM_PROMPT.includes('Vigilante AI'));
  assert.ok(DEFAULT_SYSTEM_PROMPT.includes('Evidence Vault'));
  console.log('✔ Test 2 passed: DEFAULT_SYSTEM_PROMPT contains security analyst guidelines.');
}

// Test 3: compileMcpSecurityContext compiles telemetry
{
  const context = await compileMcpSecurityContext();
  assert.ok(typeof context === 'string');
  assert.ok(context.includes('VIGILANTE LIVE TELEMETRY & MCP CONTEXT'));
  assert.ok(context.includes('Discovered Network Hosts') || context.includes('Network Reconnaissance'));
  console.log('✔ Test 3 passed: compileMcpSecurityContext aggregated real-time MCP context.');
}

// Test 4: Quick Forensic Presets
{
  assert.strictEqual(PRESET_ANALYSES.length, 5);
  const keys = PRESET_ANALYSES.map(p => p.key);
  assert.deepStrictEqual(keys, ['1', '2', '3', '4', '5']);
  assert.ok(PRESET_ANALYSES[0].prompt.includes('network hosts'));
  assert.ok(PRESET_ANALYSES[1].prompt.includes('CVE'));
  assert.ok(PRESET_ANALYSES[2].prompt.includes('Evidence Vault'));
  assert.ok(PRESET_ANALYSES[3].prompt.includes('Kubernetes'));
  assert.ok(PRESET_ANALYSES[4].prompt.includes('threat'));
  console.log('✔ Test 4 passed: Verified 5 quick forensic presets (Recon, CVEs, Triage, Pods, Threats).');
}

// Test 5: saveAnalysisReport generates markdown and metadata
{
  const topic = 'test-audit';
  const mockContent = '### Security Findings\n- Host 10.0.1.5 has open port 9200 (OpenSearch).\n- Recommend restricting access with network policies.';
  const reportRes = await saveAnalysisReport(topic, mockContent, { provider: 'ollama', model: 'llama3.2' });

  assert.ok(reportRes.filePath);
  assert.ok(reportRes.filename.includes('test-audit'));

  const fileData = await fs.readFile(reportRes.filePath, 'utf8');
  assert.ok(fileData.includes('# 🛡️ Vigilante Security & Forensics Analysis Report'));
  assert.ok(fileData.includes('Host 10.0.1.5 has open port 9200'));
  assert.ok(fileData.includes('Generated by**: ollama (llama3.2)'));

  // Clean up
  await fs.unlink(reportRes.filePath).catch(() => {});
  if (reportRes.signaturePath) {
    await fs.unlink(reportRes.signaturePath).catch(() => {});
  }
  console.log('✔ Test 5 passed: saveAnalysisReport saved formatted Markdown report in Evidence Vault.');
}

// Test 6: LLMView component export
{
  assert.ok(typeof LLMView === 'function');
  console.log('✔ Test 6 passed: LLMView React Ink component exported cleanly.');
}

console.log('🎉 All AI Security Analyst Engine tests passed successfully!');
