import assert from 'node:assert';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {
  getOllamaHost,
  compileMcpSecurityContext,
  saveAnalysisReport,
  DEFAULT_SYSTEM_PROMPT
} from '../src/engine/llm.js';
import { PRESET_ANALYSES, LLMView } from '../src/ui/LLMView.js';

console.log('🧪 Testing AI Security Analyst Engine (Ollama/Claude/GPT/Gemini)...');

// Test 1: getOllamaHost normalization
{
  const host1 = getOllamaHost({ ai: { ollama: { host: 'http://localhost:11434' } } });
  assert.strictEqual(host1, 'http://localhost:11434');

  const host2 = getOllamaHost({ ai: { ollama: { host: '192.168.1.100:11434/' } } });
  assert.strictEqual(host2, 'http://192.168.1.100:11434');
  console.log('✔ Test 1 passed: getOllamaHost correctly normalizes addresses and protocols.');
}

// Test 2: System prompt definition
{
  assert.ok(typeof DEFAULT_SYSTEM_PROMPT === 'string');
  assert.ok(DEFAULT_SYSTEM_PROMPT.includes('Vigilante AI'));
  assert.ok(DEFAULT_SYSTEM_PROMPT.includes('Evidence Vault'));
  console.log('✔ Test 2 passed: DEFAULT_SYSTEM_PROMPT contains security analyst guidelines.');
}

// Test 3: compileMcpSecurityContext compiles telemetry
{
  const context = await compileMcpSecurityContext();
  assert.ok(typeof context === 'string');
  assert.ok(context.includes('VIGILANTE LIVE TELEMETRY & MCP CONTEXT'));
  assert.ok(context.includes('Discovered Network Hosts') || context.includes('Network Reconnaissance'));
  console.log('✔ Test 3 passed: compileMcpSecurityContext aggregated real-time MCP context.');
}

// Test 4: Quick Forensic Presets
{
  assert.strictEqual(PRESET_ANALYSES.length, 5);
  const keys = PRESET_ANALYSES.map(p => p.key);
  assert.deepStrictEqual(keys, ['1', '2', '3', '4', '5']);
  assert.ok(PRESET_ANALYSES[0].prompt.includes('network hosts'));
  assert.ok(PRESET_ANALYSES[1].prompt.includes('CVE'));
  assert.ok(PRESET_ANALYSES[2].prompt.includes('Evidence Vault'));
  assert.ok(PRESET_ANALYSES[3].prompt.includes('Kubernetes'));
  assert.ok(PRESET_ANALYSES[4].prompt.includes('threat'));
  console.log('✔ Test 4 passed: Verified 5 quick forensic presets (Recon, CVEs, Triage, Pods, Threats).');
}

// Test 5: saveAnalysisReport generates markdown and metadata
{
  const topic = 'test-audit';
  const mockContent = '### Security Findings\n- Host 10.0.1.5 has open port 9200 (OpenSearch).\n- Recommend restricting access with network policies.';
  const reportRes = await saveAnalysisReport(topic, mockContent, { provider: 'ollama', model: 'llama3.2' });

  assert.ok(reportRes.filePath);
  assert.ok(reportRes.filename.includes('test-audit'));

  const fileData = await fs.readFile(reportRes.filePath, 'utf8');
  assert.ok(fileData.includes('# 🛡️ Vigilante Security & Forensics Analysis Report'));
  assert.ok(fileData.includes('Host 10.0.1.5 has open port 9200'));
  assert.ok(fileData.includes('Generated by**: ollama (llama3.2)'));

  // Clean up
  await fs.unlink(reportRes.filePath).catch(() => {});
  if (reportRes.signaturePath) {
    await fs.unlink(reportRes.signaturePath).catch(() => {});
  }
  console.log('✔ Test 5 passed: saveAnalysisReport saved formatted Markdown report in Evidence Vault.');
}

// Test 6: LLMView component export
{
  assert.ok(typeof LLMView === 'function' || typeof LLMView === 'object');
  console.log('✔ Test 6 passed: LLMView React Ink component exported cleanly.');
}

// Test 7: LLMView component render test with valid borders & theme
{
  const React = (await import('react')).default;
  const { render } = await import('ink');
  const { ThemeProvider } = await import('../src/ui/theme.js');
  const { ClipboardProvider } = await import('../src/ui/ClipboardManager.js');

  const silentStream = {
    write: () => {},
    on: () => {},
    off: () => {},
    columns: 80,
    rows: 24
  };

  const appInstance = render(
    React.createElement(
      ThemeProvider,
      null,
      React.createElement(
        ClipboardProvider,
        { isInteractive: false },
        React.createElement(LLMView, { domain: 'test.local' })
      )
    ),
    { stdout: silentStream, stderr: silentStream }
  );

  assert.ok(appInstance);
  appInstance.unmount();
  console.log('✔ Test 7 passed: LLMView rendered successfully with valid borders, timers, and theme styles.');
}

// Test 8: Empty response and invalid provider validation
{
  const { runAnalystInference } = await import('../src/engine/llm.js');

  let unsupportedCaught = false;
  try {
    await runAnalystInference({ provider: 'unsupported-provider', prompt: 'test' });
  } catch (err) {
    unsupportedCaught = true;
    assert.ok(err.message.includes('Unsupported AI provider'));
  }
  assert.ok(unsupportedCaught);
  console.log('✔ Test 8 passed: Empty response and provider validations throw informative errors.');
}

// Test 9: Multi-provider registry & provider status inspection
{
  const { SUPPORTED_PROVIDERS, getProviderStatus } = await import('../src/engine/llm.js');

  assert.ok(Array.isArray(SUPPORTED_PROVIDERS));
  assert.strictEqual(SUPPORTED_PROVIDERS.length, 7);

  const providerIds = SUPPORTED_PROVIDERS.map(p => p.id);
  assert.ok(providerIds.includes('ollama'));
  assert.ok(providerIds.includes('anthropic'));
  assert.ok(providerIds.includes('openai'));
  assert.ok(providerIds.includes('gemini'));
  assert.ok(providerIds.includes('deepseek'));
  assert.ok(providerIds.includes('groq'));
  assert.ok(providerIds.includes('openrouter'));

  // Test Ollama local status
  const ollamaStatus = getProviderStatus('ollama');
  assert.strictEqual(ollamaStatus.id, 'ollama');
  assert.strictEqual(ollamaStatus.isConfigured, true);

  // Test Cloud provider status with missing vs configured key
  const anthropicStatus = getProviderStatus('anthropic', { ai: { anthropic: { apiKey: 'test-key' } } });
  assert.strictEqual(anthropicStatus.isConfigured, true);

  const unconfiguredStatus = getProviderStatus('deepseek', { ai: { deepseek: { apiKey: '' } } });
  assert.strictEqual(unconfiguredStatus.isConfigured, false);
  assert.ok(unconfiguredStatus.statusText.includes('DEEPSEEK_API_KEY'));

  console.log('✔ Test 9 passed: SUPPORTED_PROVIDERS and getProviderStatus validated for 7 AI engines.');
}

// Test 10: Missing API key enforcement across cloud providers
{
  const { chatOpenAI, chatAnthropic, chatGemini, chatDeepSeek, chatGroq, chatOpenRouter } = await import('../src/engine/llm.js');

  const oldEnv = { ...process.env };
  delete process.env.OPENAI_API_KEY;
  delete process.env.ANTHROPIC_API_KEY;
  delete process.env.GEMINI_API_KEY;
  delete process.env.GOOGLE_API_KEY;
  delete process.env.DEEPSEEK_API_KEY;
  delete process.env.GROQ_API_KEY;
  delete process.env.OPENROUTER_API_KEY;

  let openAICaught = false;
  try {
    await chatOpenAI({ messages: [{ role: 'user', content: 'hi' }] });
  } catch (err) {
    openAICaught = err.message.includes('OpenAI API key missing');
  }
  assert.ok(openAICaught);

  let anthropicCaught = false;
  try {
    await chatAnthropic({ messages: [{ role: 'user', content: 'hi' }] });
  } catch (err) {
    anthropicCaught = err.message.includes('Anthropic API key missing');
  }
  assert.ok(anthropicCaught);

  let deepseekCaught = false;
  try {
    await chatDeepSeek({ messages: [{ role: 'user', content: 'hi' }] });
  } catch (err) {
    deepseekCaught = err.message.includes('DeepSeek API key missing');
  }
  assert.ok(deepseekCaught);

  // Restore env
  Object.assign(process.env, oldEnv);
  console.log('✔ Test 10 passed: Cloud provider API key missing errors thrown with remediation tips.');
}

console.log('🎉 All AI Security Analyst Engine tests passed successfully!');
