/**
 * Kernel-Native eBPF Lineage & Process Tree Engine
 * Reconstructs hierarchical parent-child process ancestry from runtime syscall telemetry.
 * Detects shell breakouts, LOLBin egress fetching, and container escapes.
 */

import { logger } from '../utils/logger.js';

/**
 * Build hierarchical process tree from a sequence of process/syscall events
 * @param {Array<Object>} rawEvents List of events with { pid, ppid, comm, exe, args, containerId, podName }
 * @returns {Object} Tree structure with root processes and child nodes
 */
export function buildProcessLineageTree(rawEvents = []) {
  const nodes = new Map();

  // Create node lookup
  for (const ev of rawEvents) {
    const pid = ev.pid || 1;
    const ppid = ev.ppid || 0;

    if (!nodes.has(pid)) {
      nodes.set(pid, {
        pid,
        ppid,
        comm: ev.comm || ev.exe || 'unknown',
        exe: ev.exe || ev.comm || '',
        args: ev.args || [],
        user: ev.user || 'root',
        podName: ev.podName || ev.pod || 'default-workload',
        containerId: ev.containerId || 'c-init',
        timestamp: ev.timestamp || new Date().toISOString(),
        children: [],
        anomalies: []
      });
    } else {
      // Enrich existing node
      const node = nodes.get(pid);
      if (ev.args && ev.args.length > 0) node.args = ev.args;
      if (ev.comm) node.comm = ev.comm;
      if (ev.exe) node.exe = ev.exe;
    }
  }

  // Link children to parents
  const rootNodes = [];
  for (const node of nodes.values()) {
    if (node.ppid === 0 || !nodes.has(node.ppid) || node.ppid === node.pid) {
      rootNodes.push(node);
    } else {
      const parent = nodes.get(node.ppid);
      if (parent && !parent.children.some(c => c.pid === node.pid)) {
        parent.children.push(node);
      }
    }
  }

  return {
    totalProcesses: nodes.size,
    rootCount: rootNodes.length,
    roots: rootNodes,
    nodeMap: nodes
  };
}

/**
 * Detect anomalous process executions and container breakout indicators
 * @param {Object} lineageTree Tree generated by buildProcessLineageTree
 * @returns {Array<Object>} Detected anomalies
 */
export function detectAnomalousProcessLineage(lineageTree) {
  const anomalies = [];
  const nodes = lineageTree.nodeMap ? Array.from(lineageTree.nodeMap.values()) : [];

  const SUSPICIOUS_DAEMON_PARENTS = ['nginx', 'httpd', 'apache2', 'node', 'python', 'java', 'redis-server', 'postgres', 'mysqld', 'envoy'];
  const INTERACTIVE_SHELLS = ['sh', 'bash', 'zsh', 'dash', 'csh', 'ksh'];
  const LOLBINS = ['curl', 'wget', 'nc', 'ncat', 'netcat', 'socat', 'whoami', 'id', 'uname'];

  for (const node of nodes) {
    const parent = lineageTree.nodeMap.get(node.ppid);
    const parentComm = parent ? pathBasename(parent.comm).toLowerCase() : '';
    const nodeComm = pathBasename(node.comm).toLowerCase();
    const argsStr = Array.isArray(node.args) ? node.args.join(' ') : String(node.args || '');

    // Pattern 1: Daemon or Web Server spawning interactive shell (Reverse shell / RCE)
    if (SUSPICIOUS_DAEMON_PARENTS.includes(parentComm) && INTERACTIVE_SHELLS.includes(nodeComm)) {
      anomalies.push({
        type: 'WEB_SERVER_SHELL_SPAWNED',
        severity: 'CRITICAL',
        mitreTechnique: 'T1059.004',
        mitreName: 'Command and Scripting Interpreter: Unix Shell',
        message: `Web/App daemon '${parent.comm}' (PID ${parent.pid}) spawned interactive shell '${node.comm}' (PID ${node.pid})`,
        pid: node.pid,
        ppid: node.ppid,
        args: argsStr,
        podName: node.podName
      });
      node.anomalies.push('WEB_SERVER_SHELL_SPAWNED');
    }

    // Pattern 2: Shell spawning network recon/fetching LOLBins
    if (INTERACTIVE_SHELLS.includes(parentComm) && LOLBINS.includes(nodeComm)) {
      anomalies.push({
        type: 'LOLBIN_NETWORK_FETCH',
        severity: 'HIGH',
        mitreTechnique: 'T1105',
        mitreName: 'Ingress Tool Transfer',
        message: `Shell '${parent.comm}' spawned network tool '${node.comm}' with args: '${argsStr}'`,
        pid: node.pid,
        ppid: node.ppid,
        args: argsStr,
        podName: node.podName
      });
      node.anomalies.push('LOLBIN_NETWORK_FETCH');
    }

    // Pattern 3: Container escape / sensitive socket access
    if (argsStr.includes('docker.sock') || argsStr.includes('containerd.sock') || argsStr.includes('/proc/sys/kernel/core_pattern')) {
      anomalies.push({
        type: 'CONTAINER_ESCAPE_ATTEMPT',
        severity: 'CRITICAL',
        mitreTechnique: 'T1611',
        mitreName: 'Escape to Host',
        message: `Process '${node.comm}' accessed host socket or kernel control parameter`,
        pid: node.pid,
        ppid: node.ppid,
        args: argsStr,
        podName: node.podName
      });
      node.anomalies.push('CONTAINER_ESCAPE_ATTEMPT');
    }
  }

  return anomalies;
}

/**
 * Render ASCII process hierarchy tree
 * @param {Object} node Root node
 * @param {string} [prefix='']
 * @returns {string} Formatted tree
 */
export function renderAsciiProcessTree(node, prefix = '') {
  const isAnomalous = node.anomalies && node.anomalies.length > 0;
  const badge = isAnomalous ? '🚨 [ANOMALY]' : '🟢';
  const args = node.args && node.args.length > 0 ? ` (${Array.isArray(node.args) ? node.args.join(' ') : node.args})` : '';

  let out = `${prefix}${badge} [PID ${node.pid}] ${node.comm}${args}\n`;

  if (node.children && node.children.length > 0) {
    for (let i = 0; i < node.children.length; i++) {
      const child = node.children[i];
      const isLast = i === node.children.length - 1;
      const childPrefix = prefix + (isLast ? '    └── ' : '    ├── ');
      const subPrefix = prefix + (isLast ? '        ' : '    │   ');
      out += renderAsciiProcessTree(child, childPrefix);
    }
  }

  return out;
}

function pathBasename(str) {
  if (!str) return '';
  const parts = str.split('/');
  return parts[parts.length - 1];
}
