apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-certs
  namespace: {{ include "wazuh.namespace" . }}
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
    app.kubernetes.io/component: certs
spec:
  accessModes:
    - {{ .Values.certs.persistence.accessMode | quote }}
  {{- include "wazuh.persistence.storageClass" .Values.certs.persistence.storageClass | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.certs.persistence.size | quote }}
