apiVersion: v2
name: vigil
description: Vigil SOC — open-source, AI-native Security Operations Center
type: application
version: 0.6.0
appVersion: 0.6.0
kubeVersion: '>=1.25.0-0'
home: https://vigilsoc.org
sources:
  - https://github.com/Vigil-SOC/vigil
maintainers:
  - name: Vigil-SOC
    url: https://github.com/Vigil-SOC
keywords:
  - security
  - soc
  - siem
  - ai
  - claude
  - anthropic
  - mcp
icon: https://vigilsoc.org/logo.png
annotations:
  artifacthub.io/category: security
  artifacthub.io/license: Apache-2.0
